name: binf6110
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - alsa-lib=1.2.15.3=he30d5cf_0
  - boost-cpp=1.85.0=hdad291f_4
  - bzip2=1.0.8=h4777abc_9
  - c-ares=1.34.6=he30d5cf_0
  - ca-certificates=2026.2.25=hbd8a1cb_0
  - cairo=1.18.4=h83712da_0
  - curl=8.18.0=hc57f145_1
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.17.1=hba86a56_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h8af1aa0_0
  - giflib=5.2.2=h31becfc_0
  - graphite2=1.3.14=hfae3067_2
  - harfbuzz=12.2.0=he4899c9_0
  - icu=75.1=hf9b3779_0
  - keyutils=1.6.3=h86ecc28_0
  - krb5=1.22.2=hfd895c2_0
  - lcms2=2.17=hc88f144_0
  - ld_impl_linux-aarch64=2.45.1=default_h1979696_101
  - lerc=4.0.0=hfdc4d58_1
  - libboost=1.85.0=h9fa81b4_4
  - libboost-devel=1.85.0=h37bb5a9_4
  - libboost-headers=1.85.0=h8af1aa0_4
  - libcups=2.3.3=h4f2b762_6
  - libcurl=8.18.0=hc57f145_1
  - libdeflate=1.22=h86ecc28_0
  - libedit=3.1.20250104=pl5321h976ea20_0
  - libev=4.33=h31becfc_2
  - libexpat=2.7.4=hfae3067_0
  - libffi=3.5.2=h376a255_0
  - libfreetype=2.14.1=h8af1aa0_0
  - libfreetype6=2.14.1=hdae7a39_0
  - libgcc=15.2.0=h8acb6b2_18
  - libgcc-ng=15.2.0=he9431aa_18
  - libgff=2.0.0=h1e84f2d_3
  - libglib=2.86.4=hf53f6bf_1
  - libgomp=15.2.0=h8acb6b2_18
  - libhwloc=2.12.2=default_ha470c98_1000
  - libiconv=1.18=h90929bb_2
  - libjemalloc=5.3.0=h5ad3122_1
  - libjpeg-turbo=3.1.2=he30d5cf_0
  - liblzma=5.8.2=he30d5cf_0
  - liblzma-devel=5.8.2=he30d5cf_0
  - libnghttp2=1.67.0=ha888d0e_0
  - libnsl=2.0.1=h86ecc28_1
  - libpng=1.6.55=h1abf092_0
  - libsqlite=3.51.2=h022381a_0
  - libssh2=1.11.1=h18c354c_0
  - libstdcxx=15.2.0=hef695bb_18
  - libstdcxx-ng=15.2.0=hdbbeba8_18
  - libtiff=4.7.0=hca96517_2
  - libuuid=2.41.3=h1022ec0_0
  - libwebp-base=1.6.0=ha2e29f5_0
  - libxcb=1.17.0=h262b8f6_0
  - libxcrypt=4.4.36=h31becfc_1
  - libxml2=2.14.6=h788dabe_2
  - libxml2-16=2.14.6=h8591a01_2
  - libzlib=1.3.1=h86ecc28_2
  - ncbi-vdb=3.3.0=h163da20_0
  - ncurses=6.5=ha32ae93_3
  - openjdk=25.0.1=hda3ab1e_0
  - openssl=3.6.1=h546c87b_1
  - ossuuid=1.6.2=h5ad3122_1001
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.47=hf841c20_0
  - perl=5.32.1=7_h31becfc_perl5
  - perl-alien-build=2.84=pl5321h661a7b0_1
  - perl-alien-build-plugin-download-gitlab=0.01=pl5321hdfd78af_0
  - perl-alien-libxml2=0.20=pl5321h1ae7f55_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-capture-tiny=0.48=pl5321h8af1aa0_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1011=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hd8ed1ab_0
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-path-tiny=0.124=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h86ecc28_2
  - perl-scope-guard=0.21=pl5321hd8ed1ab_0
  - perl-sub-info=0.002=pl5321hd8ed1ab_0
  - perl-term-table=0.028=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321h8af1aa0_0
  - perl-test-warnings=0.031=pl5321h8af1aa0_0
  - perl-test2-suite=0.000163=pl5321hdfd78af_0
  - perl-try-tiny=0.32=pl5321h8af1aa0_1
  - perl-uri=5.34=pl5321h8af1aa0_0
  - perl-xml-libxml=2.0210=pl5321h1ae7f55_1
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h7ac5ae9_1
  - pthread-stubs=0.4=h86ecc28_1002
  - python=3.11.14=h91f4b29_3_cpython
  - readline=8.3=hb682ff5_0
  - salmon=1.10.3=h6e0737c_5
  - setuptools=82.0.0=pyh332efcf_0
  - sra-tools=3.2.1=habe25ba_1
  - staden_io_lib=1.15.1=h346a1c6_0
  - tbb=2022.3.0=hfefdfc9_2
  - tk=8.6.13=noxft_h0dc03b3_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libice=1.1.2=h86ecc28_0
  - xorg-libsm=1.2.6=h0808dbd_0
  - xorg-libx11=1.8.13=h63a1b12_0
  - xorg-libxau=1.0.12=he30d5cf_1
  - xorg-libxdmcp=1.1.5=he30d5cf_1
  - xorg-libxext=1.3.7=he30d5cf_0
  - xorg-libxfixes=6.0.2=he30d5cf_0
  - xorg-libxi=1.8.2=h57736b2_0
  - xorg-libxrandr=1.5.5=he30d5cf_0
  - xorg-libxrender=0.9.12=h86ecc28_0
  - xorg-libxt=1.3.1=h57736b2_0
  - xorg-libxtst=1.2.5=h57736b2_3
  - xz=5.8.2=hd704e39_0
  - xz-gpl-tools=5.8.2=hd704e39_0
  - xz-tools=5.8.2=he30d5cf_0
  - zstd=1.5.7=h85ac4a6_6
prefix: /home/arwa/miniconda3/envs/binf6110
